site_name: RCJ Soccer 2022
theme:
  name: material
  palette:
    primary: green

nav:
  - Home: index.md
  - Code Submission: "code-submission.md"
  - Submission check: "submission-check.md"
  - Soccer Sim Demo Competition 2022: "demo-competition-2022.md"
  - "Soccer Sim Demo Competition 2022 Results":
    - "SoccerSim 2022 - Group Phase": "demo/demo-2022-group-phase.md"
    - "SoccerSim 2022 - Quarter Finals": "demo/demo-2022-quarter-finals.md"
    - "SoccerSim 2022 - Semifinals": "demo/demo-2022-semifinals.md"
  - Soccer Sim Code Submission: "code-submission.md"
