site_name: RCJ Soccer 2021
theme:
  name: material
  palette:
    primary: green

nav:
  - Home: index.md
  - Soccer Sim Demo Competition 2022: "demo-competition-2022.md"
  - Soccer Sim Code Submission: "code-submission.md"
